# -*- coding: utf-8 -*-
"""CSST101_R_Project_Part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkyE90gq6GnXMirvrb2cTgJ0d6rBwDDf

# 1. Data Frame
"""

import pandas as pd

students = pd.DataFrame({
  "StudentID": ["SOO1","SOO2","SOO3","SOO4","SOO5"],
  "Attendance": [95,72,88,79,68],
  "Grade": [90,70,85,77,65],
  "Risk": ["Low Risk","High Risk","Low Risk","Moderate Risk","High Risk"]
})

print(students)
students.to_csv("students.csv", index=False)

"""# 2. Creating Variables"""

student = {
    "Name": "student",
    "Attendance": 95,
    "Grade": 90,
    "Risk": "Low Risk"
}

"""# 3. Basic Calculations"""

quiz_score = 85
laboratory_score = 90
project_score = 88
exam_score = 80

quiz_weight = 0.20
laboratory_weight = 0.25
project_weight = 0.25
exam_weight = 0.30

final_grade = (quiz_score * quiz_weight) + \
              (laboratory_score * laboratory_weight) + \
              (project_score * project_weight) + \
              (exam_score * exam_weight)

print(f"Final Grade: {final_grade:.2f}")

if final_grade < 75:
  print("Failed")
else:
  print("Passed")

"""# 4. Using Comparison Operators"""

grade = 70
attendance = 72

grade < attendance
grade > attendance
grade == attendance
grade <= attendance
grade >= attendance
grade != attendance

"""# 5. AND and OR"""

attendance <- 72
grade <- 70

if(attendance & grade < 75){
  print("At Risk")
}else if(attendance | grade < 75){
  print("At Risk")
}else{
  print("Not at risk")
}

"""#6. Simple IF Statement"""

grade <- 75

if(grade < 75)(
  print ("Failed")
)else(
print ("PASSED")
)

"""# 7. Mutliple Conditions"""

grade <- 94

if (grade >= 90 && grade <= 100) {
  print ("Excellent")
} else if (grade >= 85 && grade <= 89) {
  print ("Very Good")
} else if (grade >= 80 && grade <= 84) {
  print ("Good")
} else if (grade >= 75 && grade <= 79) {
  print ("Passed")
} else {
  print ("Failed")
}

"""# 8. Creating Functions"""

def classify_grade(grade):
    if 90 <= grade <= 100:
        print("Excellent")
    elif 85 <= grade <= 89:
        print("Very Good")
    elif 80 <= grade <= 84:
        print("Good")
    elif 75 <= grade <= 79:
        print("PASSED")
    else:
        print("Failed")

classify_grade(75)

"""# 9. Creating a Data Frame"""

students <- data.frame(
    student_ID = c("S001", "S002", "S003", "S004", "S005"),
    Attendance = c(95, 72, 88, 79, 68),
    Grade = c(90, 70, 85, 77, 65)
)

students

"""#10. Adding a Classification Column"""

import numpy as np

students['Performance'] = np.where(
  students['Grade'] >= 80,
  "Good",
  np.where(
    students['Grade'] >= 75,
    "Passed",
    "False"
  )
)

print(students)

"""#11. Creating a Simple Rule-Based System"""

classify_risk <- function(attendance, grade){

  if (attendance <75 & grade <75){
    print("High risk")
  }else{
    print ("Low risk")
  }
}

classify_risk(80, 90)

"""#12. Add More Rules"""

student_risk <- function(attendance, grade){

if (attendance <75 & grade <75){
  print("High risk")
}else if (attendance <85 | grade <80){
  print("Moderate risk")
}else if(attendance >= 85 & grade >= 80){
  print("low risk")
}else{}

}

student_risk(85, 80)

"""#13. Apply the Rule to Multiple Student"""

students$Risk <- mapply(
  student_risk,
  students$Attendance,
  students$Grade
)

students

"""#13. Count the Result"""

table(students$Risk)

"""1. 2 students are in High Risk
2. 1 student in moderate risk
3. 2 are in Low Risk
4. High risk and Low riskhas the largest number of students

#14. Create Visualization
"""

risk_counts <- table(students$Risk)

barplot(
  risk_counts,
  main = "Student Risk Classification",
  xlab = "Risk level",
  ylab = "Number of Students"
)

"""1. The graph shows the Students Risk Classification
2. High Risk and Low Risk has the most students.
3. encourage the students to be academically active to prevent students in such risk.

#15. Add Recommendation
"""

recommend_risk <- function(risk){

  if (risk == "High risk"){
    return ("Immediate academic intervention")
  } else if( risk == "Moderate risk"){
    return("Academic Monitoring")
  } else if( risk == "Low risk"){
      return ("Continue regular monitoring")
  }

}
recommend_risk("High risk")

"""# 16. Mini KRR System/Final System"""

student_risk <- function(attendance, grade){

if (attendance <75 & grade <75){
  print("High risk")
}else if (attendance <85 | grade <80){
  print("Moderate risk")
}else if(attendance >= 85 & grade >= 80){
  print("low risk")
}else{}

}

recommend_risk <- function(risk){

  if (risk == "High risk"){
    return ("Immediate academic intervention")
  } else if( risk == "Moderate risk"){
    return("Academic Monitoring")
  } else if( risk == "Low risk"){
      return ("Continue regular monitoring")
  }

}
recommend_risk("High risk")

students <- data.frame(
  student_ID = c("S001", "S002", "S003", "S004", "S005"),
  Attendance = c(95, 72, 88, 79, 68),
  Grade = c(90, 70, 85, 77, 65)
)

student_risk <- function(attendance, grade) {

  if (attendance < 75 & grade < 75) {
    return("High risk")

  } else if (attendance < 85 | grade < 80) {
    return("Moderate risk")

  } else {
    return("Low risk")
  }
}

recommend_risk <- function(risk) {

  if (risk == "High risk") {
    return("Immediate academic intervention")

  } else if (risk == "Moderate risk") {
    return("Academic monitoring")

  } else {
    return("Continue regular monitoring")
  }
}

mini_krr <- function(student_id, attendance, grade) {

  risk <- student_risk(attendance, grade)
  recommendation <- recommend_risk(risk)

  cat("Student ID:", student_id, "\n")
  cat("Attendance:", attendance, "%\n")
  cat("Grade:", grade, "\n")
  cat("\nRisk Level:", risk, "\n")
  cat("\nRecommendation:\n", recommendation, "\n")
}

mini_krr("S002", 72, 70)