# -*- coding: utf-8 -*-
"""CSST102_Exer2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqtT3YmT_vaCEoAwVYkp76veOzRX5mSC

#**Machine Learning Pipeline**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import f_classif

"""#LOAD AND UNDERSTAND THE DATASETS"""

#convert to dataframe
df = pd.read_csv("UCI_Wine_Dataset_178.csv")

df.head(150)

df.info()

df.describe()

df.drop(columns="ID", inplace=True)

df['class'].value_counts()

"""#Visualize the dataset

#Histogram
"""

plt.hist(df['Alcohol'])
plt.xlabel("Alcohol")
plt.ylabel("Number of Rows")
plt.show()

plt.hist(df['Malicacid'])
plt.xlabel("Malicacid")
plt.ylabel("Number of Rows")
plt.show()

"""#Scatter Plot"""

colors = {1: 'red',
          2: 'blue',
          3: 'green'}

plt.scatter(df['Alcohol'], df['Malicacid'], c=df['class'].map(colors))
plt.xlabel("Alcohol")
plt.ylabel("Malicacid")
plt.show()

"""#Split the Dataset into a training set and testing set"""

X = df.drop("class", axis=1)

y = df["class"].values

F,p = f_classif(X,y)

feature_scores = pd.DataFrame({
    "Feature": X.columns,
    "F-Score": F,
    "P-Value": p
})

feature_scores = feature_scores.sort_values(by="F-Score", ascending=False)
feature_scores

top_features = feature_scores.head(5)

plt.figure(figsize=(10,5))

plt.bar(
    top_features["Feature"],
    top_features["F-Score"]
)

plt.xticks(rotation=45)
plt.xlabel("Feature")
plt.ylabel("F-Score")
plt.title("Top 5 Features")
plt.show()

#features
x = df.drop(columns=["class"]).values

#labels
y = df["class"].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

print(x_train)

"""# Create the Model

#Choose machine learning Algorithm
"""

knn = KNeighborsClassifier(n_neighbors=27)

knn.fit(x_train, y_train)

"""#Test the Model"""

y_pred = knn.predict(x_test)

# Accuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Precision
precision = metrics.precision_score(y_test, y_pred, average='weighted')
print('\nPrecision:', precision)

# Recall
recall = metrics.recall_score(y_test, y_pred, average='weighted')
print('\nRecall:', recall)

# F1-Score
f1 = metrics.f1_score(y_test, y_pred, average='weighted')
print('\nF1-Score:', f1)

"""#Display the confusion matrix"""

metrics.confusion_matrix(y_test, y_pred)

"""#Test the Model(Prediction)"""

knn.predict([[1.24,3.22,3.52,7.22,5.25,3.62,7.25,9.22,9.61,11.23,11.93,15.22,13.62]])